// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.887
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"ki/src/config"
	"ki/src/pkg/bytes"
	"ki/src/ui"
	"ki/src/ui/formkeys"
)

func e2eOptions(view *PageUploadView) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<br><h1>E2E options</h1><br><pre class=\"my-2\" title=\"GPG command to encrypt a file with a password\"><textarea class=\"w-full\" rows=\"1\">gpg -c your_file.txt</textarea></pre><pre class=\"my-2\" title=\"7-Zip command to encrypt a file with a password\"><textarea class=\"w-full\" rows=\"1\">7z a output.7z -pyour_password your_file.txt</textarea></pre>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func formUploadScript() templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_formUploadScript_bb14`,
		Function: `function __templ_formUploadScript_bb14(){const CHUNK_THRESHOLD = 1;//50 * 1024 * 1024; // use chunked API for files larger than 50 MB

    document.addEventListener('DOMContentLoaded', () => {

        const form = document.querySelector('form[action="/api/upload"]');

        if (!form) {
            return;
        }

        form.addEventListener('submit', (event) => {
            event.preventDefault();

            const fileInput = form.querySelector('input[type="file"]');
            const file = fileInput && fileInput.files[0];

            if (file && file.size > CHUNK_THRESHOLD) {
                doChunkedUpload(form, file);
            } else {
                doSingleUpload(form);
            }
        });
    });

    function makeProgressUI(form) {
        const cont = document.createElement('div');
        cont.style.display = 'flex';
        cont.style.alignItems = 'center';
        cont.style.justifyContent = 'center';
        cont.style.gap = '10px';

        const prog = document.createElement('div');
        prog.style.whiteSpace = 'pre';
        prog.style.fontFamily = 'monospace';

        const cancel = document.createElement('button');
        cancel.type = 'button';
        cancel.textContent = 'Cancel';
        cancel.style.cursor = 'pointer';

        cont.appendChild(prog);
        cont.appendChild(cancel);
        form.parentElement.insertBefore(cont, form);

        return { cont, prog, cancel };
    }

    function fmtProgress(loaded, total, startTime) {
        const percent = ((loaded / total) * 100).toFixed(1);
        const rateBps = (loaded / ((Date.now() - startTime) / 1000)) / 1024;
        const rateStr = rateBps > 1024
            ? (rateBps / 1024).toFixed(2) + ' MB/s'
            : rateBps.toFixed(1) + ' KB/s';
        return ` + "`" + `${loaded} / ${total} bytes (${percent}%) @ ${rateStr}` + "`" + `;
    }

    function doSingleUpload(form) {
        const { cont, prog, cancel } = makeProgressUI(form);
        const xhr = new XMLHttpRequest();
        const startTime = Date.now();

        cancel.onclick = () => { xhr.abort(); cont.remove(); };

        xhr.open(form.method, form.action, true);
        xhr.setRequestHeader('X-Requested-With', 'js-form');

        xhr.upload.onprogress = (e) => {
            if (e.lengthComputable) {
                prog.textContent = fmtProgress(e.loaded, e.total, startTime);
            }
        };

        xhr.onload = () => {
            const location = xhr.getResponseHeader('Location');
            if (location && xhr.status === 200) {
                window.location.href = location;
            } else {
                cont.remove();
                alert('Upload failed: ' + xhr.status);
            }
        };

        xhr.onerror = () => { cont.remove(); alert('Network error during upload.'); };

        xhr.send(new FormData(form));
    }

    async function doChunkedUpload(form, file) {
        const { cont, prog, cancel } = makeProgressUI(form);
        let uploadId = null;
        let aborted = false;

        cancel.onclick = async () => {
            aborted = true;
            if (uploadId) {
                fetch('/api/upload/' + uploadId + '/abort', { method: 'POST' }).catch(() => {});
            }
            cont.remove();
        };

        prog.textContent = 'Starting upload...';

        // 1. Begin: send metadata only.
        const beginData = new FormData();
        beginData.set('__csrf__',           form.querySelector('[name="__csrf__"]').value);
        beginData.set('expire_days',        form.querySelector('[name="expire_days"]').value);
        beginData.set('expire_hours',       form.querySelector('[name="expire_hours"]').value);
        beginData.set('expire_minutes',     form.querySelector('[name="expire_minutes"]').value);
        beginData.set('expire_downloads',   form.querySelector('[name="expire_downloads"]').value);
        beginData.set('memory_only',        form.querySelector('[name="memory_only"]').value);
        beginData.set('password_2_download', form.querySelector('[name="password_2_download"]').value);
        beginData.set('filename',           file.name);

        let beginResp;
        try {
            beginResp = await fetch('/api/upload/begin', { method: 'POST', body: beginData });
        } catch (e) {
            cont.remove();
            alert('Network error during upload.');
            return;
        }
        if (!beginResp.ok) {
            cont.remove();
            alert('Upload failed: ' + await beginResp.text());
            return;
        }

        const { upload_id, max_chunk_size } = await beginResp.json();
        uploadId = upload_id;
        const chunkSize = max_chunk_size || (10 * 1024 * 1024);

        // 2. Send chunks sequentially.
        let offset = 0;
        const total = file.size;
        const startTime = Date.now();

        while (offset < total) {
            if (aborted) return;

            const chunk = file.slice(offset, offset + chunkSize);

            let chunkResp;
            try {
                chunkResp = await fetch('/api/upload/' + uploadId + '/chunk', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/octet-stream' },
                    body: chunk,
                });
            } catch (e) {
                cont.remove();
                alert('Network error during upload.');
                return;
            }
            if (!chunkResp.ok) {
                cont.remove();
                alert('Upload failed: ' + await chunkResp.text());
                return;
            }

            offset += chunk.size;
            prog.textContent = fmtProgress(offset, total, startTime);
        }

        if (aborted) return;

        // 3. Complete.
        prog.textContent = 'Finalising...';

        let completeResp;
        try {
            completeResp = await fetch('/api/upload/' + uploadId + '/complete', {
                method: 'POST',
                headers: { 'X-Requested-With': 'js-form' },
            });
        } catch (e) {
            cont.remove();
            alert('Network error during upload.');
            return;
        }

        if (completeResp.ok) {
            const location = completeResp.headers.get('Location');
            if (location) {
                window.location.href = location;
                return;
            }
        }

        cont.remove();
        alert('Upload failed: ' + completeResp.status);
    }
}`,
		Call:       templ.SafeScript(`__templ_formUploadScript_bb14`),
		CallInline: templ.SafeScriptInline(`__templ_formUploadScript_bb14`),
	}
}

func PageUpload(view *PageUploadView) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var3 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = formUploadScript().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " <br><h1>Upload a file</h1><h3>File must be less than ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(bytes.PrettyByteSize64(config.MaxUploadSize()))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `src/ui/pages/page_upload.templ`, Line: 232, Col: 83}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</h3><br><form enctype=\"multipart/form-data\" action=\"/api/upload\" method=\"POST\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = ui.CSRF(view.R).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<table class=\"table-auto table-padded\"><tbody class=\"text-right\"><tr title=\"Expire after this many days\"><td class=\"px-2\">Days </td><td><input class=\"w-full\" type=\"number\" name=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(formkeys.UPLOAD_FORM_EXPIRE_DAYS)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `src/ui/pages/page_upload.templ`, Line: 245, Col: 100}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\" value=\"0\" min=\"0\" required></td></tr><tr title=\"Expire after this many hours\"><td class=\"px-2\">Hours </td><td><input class=\"w-full\" type=\"number\" name=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var6 string
			templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(formkeys.UPLOAD_FORM_EXPIRE_HOURS)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `src/ui/pages/page_upload.templ`, Line: 249, Col: 101}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "\" value=\"1\" min=\"0\" required></td></tr><tr title=\"Expire after this many minutes\"><td class=\"px-2\">Minutes </td><td><input class=\"w-full\" type=\"number\" name=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var7 string
			templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(formkeys.UPLOAD_FORM_EXPIRE_MINUTES)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `src/ui/pages/page_upload.templ`, Line: 253, Col: 103}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "\" value=\"0\" min=\"0\" required></td></tr><tr title=\"Expired after this many downloads\"><td class=\"px-2\">Downloads </td><td><input class=\"w-full\" type=\"number\" name=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var8 string
			templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(formkeys.UPLOAD_FORM_EXPIRE_DOWNLOADS)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `src/ui/pages/page_upload.templ`, Line: 257, Col: 105}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "\" value=\"1\" min=\"1\" required></td></tr><tr title=\"Never write file metadata to disk (file will expire if server restarts or crashes)\"><td class=\"px-2\">Memory Only </td><td><select class=\"w-full\" name=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var9 string
			templ_7745c5c3_Var9, templ_7745c5c3_Err = templ.JoinStringErrs(formkeys.UPLOAD_FORM_MEMORY_ONLY)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `src/ui/pages/page_upload.templ`, Line: 262, Col: 86}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var9))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "\"><option value=\"false\">No</option> <option value=\"true\">Yes</option></select></td></tr><tr title=\"Require this password to download the file\"><td class=\"px-2\">Password (Optional) </td><td><input class=\"w-full\" type=\"password\" name=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var10 string
			templ_7745c5c3_Var10, templ_7745c5c3_Err = templ.JoinStringErrs(formkeys.UPLOAD_FORM_PASSWORD)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `src/ui/pages/page_upload.templ`, Line: 270, Col: 99}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var10))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "\"></td></tr><tr title=\"Choose the file to upload\"><td colspan=\"2\"><input class=\"w-full\" type=\"file\" name=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var11 string
			templ_7745c5c3_Var11, templ_7745c5c3_Err = templ.JoinStringErrs(formkeys.UPLOAD_FORM_FILE)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `src/ui/pages/page_upload.templ`, Line: 274, Col: 90}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var11))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "\" required></td></tr><tr title=\"Upload the selected file\"><td colspan=\"2\"><input class=\"w-full\" type=\"submit\" value=\"Upload\"></td></tr></tbody></table></form>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = e2eOptions(view).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Base(&view.BaseView).Render(templ.WithChildren(ctx, templ_7745c5c3_Var3), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
