package config

const ENV__USER_REGISTRY_PATH = "KI_USER_REGISTRY_PATH"
const ENV__TRUSTED_PROXIES = "KI_TRUSTED_PROXIES"
const ENV__BIND_ADDR = "KI_BIND_ADDR"
const ENV__PORT = "KI_PORT"
const ENV__MAX_UPLOAD_SIZE = "KI_MAX_UPLOAD_SIZE"
